# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

arma_weighted_mean <- function(x, w) {
    .Call('diagis_arma_weighted_mean', PACKAGE = 'diagis', x, w)
}

arma_running_mean <- function(x) {
    .Call('diagis_arma_running_mean', PACKAGE = 'diagis', x)
}

arma_running_weighted_mean <- function(x, w) {
    .Call('diagis_arma_running_weighted_mean', PACKAGE = 'diagis', x, w)
}

arma_weighted_var <- function(x, w, ml) {
    .Call('diagis_arma_weighted_var', PACKAGE = 'diagis', x, w, ml)
}

arma_running_var <- function(x, ml) {
    .Call('diagis_arma_running_var', PACKAGE = 'diagis', x, ml)
}

arma_running_weighted_var <- function(x, w, ml) {
    .Call('diagis_arma_running_weighted_var', PACKAGE = 'diagis', x, w, ml)
}

